import {
  File,
  Pencil,
  Trash2,
  ArrowUp,
  Search,
  Globe,
  TerminalSquare,
  Brain,
  Download,
  ChevronsUpDown,
  Code2,
  ChevronRight,
  CircleAlert,
  X,
  Copy,
  Paperclip,
  Square,
  Send,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  file: File,
  edit: Pencil,
  delete: Trash2,
  "arrow-up": ArrowUp,
  search: Search,
  globe: Globe,
  terminal: TerminalSquare,
  brain: Brain,
  download: Download,
  "chevron-up-down": ChevronsUpDown,
  code: Code2,
  "chevron-right": ChevronRight,
  error: CircleAlert,
  close: X,
  copy: Copy,
  attachment: Paperclip,
  stop: Square,
  send: Send,
};

export type IconName = keyof typeof ICON_MAP | (string & {});
